@startuml

!include ../theme.puml

entity Topic {
    * id
    --
    name
}

entity RevisionLog {
    * id
    --
    revisionDate
    durationMinutes
    revisionMethod
    confidenceLevel
    notes
}

Topic ||--o{ RevisionLog : contains

@enduml